name: map check
on: push
jobs:
  my_job:
    name: check maps for absolute paths and undo/redo history
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: |
        ls
        ${{ github.workspace }}/scripts/paths_util.py ${{ github.workspace }} -u
